#!/usr/bin/env bash
# Install NGINX and configure it
sudo apt-get  update
sudo apt-get -y install nginx
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/index.html
sudo service nginx restart
