#!/usr/bin/env bash
# Install NGINX and configure it
sudo apt-get -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP' #Permisos para el puerto 80
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/
sudo service nginx restart
