#!/bin/bash
.TH man 2 “07 Jun 2020” “0,32” “holberton man page”

.SH NAME

.B            Holberton – become a full-stack software engineer.

.SH SYNOPSIS

              Holberton  (STUDENTNAME)

.SH DESCRIPTION

               Holberton School is a Project-based alternativ to college for the next generation of software engineers.

.SH OPTIONS

.B                Holberton does not take any options. However, you can supply studentname.

.SH SEE ALSO

.I                 Peerlearning(2), projectbased(2), fullstack(2), Betty(1)

.SH BUGS

                  No known bugs.

.SH AUTHOR

                   Julien Barbier, Sylvain Kalache, Sophie Barbier, Guillaume Salva, Kris Bredemeir, Julien Cyr, Alex Gautier and all the Holberton mentors