#!/usr/bin/env bash
# While use to display 10 times a string
counter=0
while [ $counter -lt 10 ]; do
   if test $counter -eq 9
   then
   echo hi
   fi
   echo Holberton School
   (( counter++ ))
done
