#!/usr/bin/env bash
# While use to display 10 times a string
counter=0
while [ $counter -lt 10 ]; do
   if [ $counter -eq 3 ]
   then
     echo "bad luck"
   elif  [ $counter -eq 7 ]
   then
     echo "good luck"
   else
     echo "Holberton School"
   fi
   (( counter++ ))
done
